AzureSQL redirect
kardeiz/bb8-tiberius pull request #3
Opened 2021-05-07 18:51 UTC by windoze

Support AzureSQL redirect

2021-05-09 11:10 UTC, windoze commented
Hi @kardeiz, would you like to take a look?
Thanks.

2021-05-11 01:38 UTC, kardeiz requested changes
@windoze Looks good, thanks! I've requested a minor change on two lines.

2021-05-11 01:38 UTC, kardeiz commented on src/lib.rs
> +            tcp.set_nodelay(true)?;
@windoze You can drop this; the `set_nodelay` is performed in the next line `(self.modify_tcp_stream)(&tcp)?;`. Please do so for the line in the `async_std` impl as well.

2021-05-11 16:56 UTC, windoze commented
Thanks for your reply, I didn't see it 😄 

Redundant set_nodelay removed.

2021-05-11 23:36 UTC, kardeiz approved these changes
Thanks! I'm merging this and will release a `0.5.2` in a bit.

2021-05-11 23:37 UTC, merged